#include <cmath>
#define _DCAPP_EXTERNALS_
#include "dcapp.hh"

void docking_logic(void)
{
    if (*ORION_TO_VESTIBULE_HATCH_FLOW_RATE > 0.05) *ORION_TO_VESTIBULE_HATCH_FLOW_POS = 1;
    else *ORION_TO_VESTIBULE_HATCH_FLOW_POS = 0;
    if (*ORION_TO_VESTIBULE_HATCH_FLOW_RATE < -0.05) *ORION_TO_VESTIBULE_HATCH_FLOW_NEG = 1;
    else *ORION_TO_VESTIBULE_HATCH_FLOW_NEG = 0;
    *ORION_TO_VESTIBULE_HATCH_FLOW_RATE_DISP = fabs(*ORION_TO_VESTIBULE_HATCH_FLOW_RATE);

    if (*EAM_TO_VESTIBULE_HATCH_FLOW_RATE > 0.05) *EAM_TO_VESTIBULE_HATCH_FLOW_POS = 1;
    else *EAM_TO_VESTIBULE_HATCH_FLOW_POS = 0;
    if (*EAM_TO_VESTIBULE_HATCH_FLOW_RATE < -0.05) *EAM_TO_VESTIBULE_HATCH_FLOW_NEG = 1;
    else *EAM_TO_VESTIBULE_HATCH_FLOW_NEG = 0;
    *EAM_TO_VESTIBULE_HATCH_FLOW_RATE_DISP = fabs(*EAM_TO_VESTIBULE_HATCH_FLOW_RATE);

    *ORION_TO_VESTIBULE_MPEV_FLOW_DISP = fabs(*ORION_TO_VESTIBULE_MPEV_FLOW_RATE);
    *EAM_TO_VESTIBULE_MPEV_FLOW_DISP = fabs(*EAM_TO_VESTIBULE_MPEV_FLOW_RATE);
    if(fabs(*ORION_TO_EAM_VESTIBULE_FLOW_RATE)>fabs(*ORION_TO_EAM_VESTIBULE_IMV_FLOW_RATE)) *ORION_TO_EAM_VESTIBULE_FLOW_DISP = fabs(*ORION_TO_EAM_VESTIBULE_FLOW_RATE);
    else *ORION_TO_EAM_VESTIBULE_FLOW_DISP = fabs(*ORION_TO_EAM_VESTIBULE_IMV_FLOW_RATE);
}
